<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>LoginApp-Windows7-11</AssemblyName>
    <RootNamespace>LoginApp</RootNamespace>
  </PropertyGroup>
</Project>
